liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    filter_sets:
        open_marketplace_fixture_size:
            filters:
                thumbnail: { size: [800, 600], mode: outbound }
        open_marketplace_vendor_background:
            filters:
                thumbnail: { size: [1155, 200], mode: outbound }
