open_marketplace_shop_vendor_page:
    resource: "routing/vendor_page.yaml"
    prefix: /{_locale}/vendors
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
