open_marketplace_admin_resources:
    resource: "routing/resources.yaml"

open_marketplace_admin_messaging:
    resource: "routing/messaging.yaml"

open_marketplace_admin_product_listing:
    resource: "routing/product_listing.yaml"

open_marketplace_admin_vendor:
    resource: "routing/vendor.yaml"
